# Generated by Django 4.2.3 on 2023-07-29 13:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model", models.CharField(max_length=200)),
                (
                    "brand",
                    models.CharField(
                        choices=[("bmw", "BMW"), ("ford", "Ford")], max_length=50
                    ),
                ),
                (
                    "main_color",
                    models.CharField(
                        choices=[("red", "Red"), ("blue", "Blue")], max_length=50
                    ),
                ),
                ("value", models.IntegerField()),
                ("production_cost", models.IntegerField()),
                ("transportation_cost", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
